//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni2_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinicPatient
    {
        public int patientId { get; set; }
        public string cardNumber { get; set; }
        public System.DateTime expiryDate { get; set; }
        public Nullable<bool> hasVirus { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> doctorId { get; set; }
    
        public virtual tblClinicDoctor tblClinicDoctor { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
