//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni2_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int reportId { get; set; }
        public System.DateTime reportDate { get; set; }
        public string description { get; set; }
        public int totalTime { get; set; }
        public Nullable<int> maintenanceId { get; set; }
    
        public virtual tblClinicMaintenance tblClinicMaintenance { get; set; }
    }
}
