//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni2_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClinicDoctor
    {
        public int userId { get; set; }
        public string fullname { get; set; }
        public string ICnumber { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string gender { get; set; }
        public string citizenship { get; set; }
        public string account { get; set; }
        public bool admissionOfPatients { get; set; }
        public string department { get; set; }
        public int doctorId { get; set; }
        public Nullable<int> managerId { get; set; }
        public string shift { get; set; }
        public int floorNumber { get; set; }
        public int maxNumberOfDoctors { get; set; }
        public int minNumberOfRooms { get; set; }
        public Nullable<int> numberOfOmissions { get; set; }
    }
}
